# Generated by Django 5.2 on 2025-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_alter_buggy_assigned_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="buggy",
            name="capacity",
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
